#!/bin/sh
set -e 

KDESU_ORIG=/usr/lib/kde4/libexec/kdesu
KDESU_DEST=/usr/lib/kde4/libexec/kdesu.kde

KDESU_MAN_ORIG=/usr/share/man/man1/kdesu.1.gz
KDESU_MAN_DEST=/usr/share/man/man1/kdesu.kde.1.gz

case "$1" in
	configure)

	debconf=
	if [ -f /usr/share/debconf/confmodule ]; then
		. /usr/share/debconf/confmodule
		debconf=yes
	fi

	if [ $debconf ]; then
		db_get kdesudo/kdesu
		case "$RET" in
		true)
			if ! dpkg-divert --list ${KDESU_ORIG} | grep -q ${KDESU_ORIG}
			then
				dpkg-divert --package kdesudo --divert ${KDESU_DEST} --rename ${KDESU_ORIG}
				dpkg-divert --package kdesudo --divert ${KDESU_MAN_DEST} --rename ${KDESU_MAN_ORIG}
				ln -s kdesudo ${KDESU_ORIG}
				ln -s kdesudo.1.gz ${KDESU_MAN_ORIG}
			fi
		;;
		false)
			if dpkg-divert --list ${KDESU_ORIG} | grep -q "by kdesu"
			then
				if [ -L ${KDESU_ORIG} ]
				then
					if [ "$(readlink -f ${KDESU_ORIG})" = "/usr/bin/kdesudo" ]
					then
						rm ${KDESU_ORIG}
						rm ${KDESU_MAN_ORIG}
					fi
				fi
				if [ ! -e ${KDESU_ORIG} ]
				then
					dpkg-divert --package kdesudo --rename --remove ${KDESU_ORIG}
					dpkg-divert --package kdesudo --rename --remove ${KDESU_MAN_ORIG}
				fi
			fi

		;;
		esac
	fi
	;;
    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac


#DEBHELPER#

exit 0
