#! /bin/sh

set -e

package_name=kdesudo

if [ -z "$package_name" ]; then
    print >&2 "Internal Error. Please report a bug."
    exit 1;
fi

case "$1" in
  install)
    dpkg-divert --package $package_name \
    --divert /usr/lib/kde4/libexec/kdesu.distrib \
    --rename /usr/lib/kde4/libexec/kdesu
    ;;
  abort-upgrade)
    ;;
  *) echo "$0: didn't understand being called with \`$1'" 1>&2
     exit 0;;
esac

exit 0
